version: '3'
services:
    eai_node:
        image: "solderneer/eai_node"
        ports:
         - "8002:3000"
        restart: "always"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        volumes: 
         - "redis_data:/data"
	entrypoint: "redis-server --appendonly yes"
        restart: "always"
    watchtower:
        image: "v2tec/watchtower"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "always"
volumes:
    redis_data:
