version: '3'
services:
    eai_node:
        image: "solderneer/eai_node"
        ports:
         - "3000:3000"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        volumes: 
         - "redis_data:/data"
    watchtower:
        image: "v2tec/watchtower"
        volumes:
          - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "unless-stopped"
volumes:
    redis_data:
