version: '3'
services:
    eai_node:
        image: "solderneer/eai_node"
        expose:
         - "3000"
        restart: "always"
        networks:
         - "web"
         - "default"
        labels:
         - "traefik.backend=eainode"
         - "traefik.docker.network=web"
         - "traefik.enable=true"
         - "traefik.frontend.rule=Host:eainode.solderneer.me"
         - "traefik.port=3000"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        labels:
         - "traefik.enable=false"
        volumes: 
         - "redis_data:/data"
        entrypoint: "redis-server --appendonly yes"
        restart: "always"
    watchtower:
        image: "v2tec/watchtower"
        volumes:
         - "/var/run/docker.sock:/var/run/docker.sock"
        restart: "always"
volumes:
    redis_data:

networks:
    web:
        external: true
