version: '3'
services:
    eai_node:
        image: "solderneer/eai_node"
        port:
         - "3000:3000"
    redis:
        image: "redis"
        port:
         - "6379:6379"
        volumes: 
         - "redis_data:/data"
volumes:
    redis_data: