version: '3'
services:
    eai_node:
        image: "solderneer/eai_node"
        ports:
         - "8002:3000"
    redis:
        image: "redis"
        ports:
         - "6379:6379"
        volumes: 
         - "redis_data:/data"
volumes:
    redis_data:
